version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teyvatexp_auth_server
    depends_on:
      - postgres
      - redis
    environment:
      APP_PORT: 8080
      DB_URL: jdbc:postgresql://postgres:5432/dev_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    restart: always

  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:7
    container_name: my_redis
    volumes:
      - redisdata:/data
    ports:
      - "6380:6379"
    restart: always

volumes:
  pgdata:
  redisdata:
