spring:
  session:
    redis:
      namespace: teyvatexp:session
      flush-mode: on_save
      save-mode: on_set_attribute
    timeout: 1800
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  security:
    oauth2:
      authorizationserver:
        client:
          # Test client for development purpose
          public-client:
            registration:
              client-id: "public-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://localhost:5173/callback"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: false
            require-proof-key: true
        issuer: http://localhost:${APP_PORT}